version: 2.1
orbs:
  slack: circleci/slack@4.1.1
workflows:
  slack_integration_testing:
    jobs:
      -  deploy_network_tier:
           context:
             - aws
             - slack

jobs:
  deploy_network_tier:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "Network Infra Deploy"
          command:
            aws cloudformation deploy --stack-name $NETWORK_STACK_NAME --template-file $NETWORK_STACK_TEMPLATE --parameter-overrides file://$NETWORK_STACK_PARAMS   
      - slack/notify:
          event: fail
          mentions: '@marios.subscriptions'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1


